name: MerchantShops
main: github.shor_van.merchantshops.MerchantShops
version: 1.0.15 b85 (1.13.2)
api-version: 1.13
commands:
    shop:
        description: main command to modify the shops.
        usage: /<shop> <addmerchant|removemerchant|merchant|listmerchants|help>