name: MerchantShops
main: github.shor_van.merchantshops.MerchantShops
version: 1.3.0 b108 (1.14)
api-version: 1.14
commands:
    shop:
        description: main command to modify the shops.
        usage: /<shop> <addmerchant|removemerchant|merchant|listmerchants|help>